displayName=Shrimp Lock
author=ErnestDongleheim
description=Disables the Eat option on all food except Shrimps
tags=food,shrimp,eat,menu
version=4.2.0
plugins=com.shrimplock.ShrimpLockPlugin
build=standard
